### ISSUE TITLE
Decouple GUI from backend

### ISSUE THREAD

**Issue by ata2001** [Pext/Pext#100]
Currently the Qt interface is tied closely to Pext. There are several downsides to this. Not only, that we can't create alternative user interfaces, the current structure makes it very hard to cover the code with unit tests. I propose separating the frontend from the backend, with the possibility of future non-Qt UIs and test coverage in mind.

This shouldn't obligate changes in the module API I think, but perhaps we could change the way it is implemented, to make sharing code between frontends easier.

We should start by breaking down the Window class, moving the Qt related parts to a different file and leaving as much as it makes sense in the main pext class.

**Comment by TheLastProject** [comment]
I consider this resolved after the following commits:
a4221eac9faae932125cc23ff3d40eae2ac148ac
efad99b5ff83105f9327ba074961480433ccc720
532258a014f17a6789d4f98832cb2518e00dea6d
c71db3d6d97f378ba9f840fe0cb0f3e0708184cb
30af97d6e6ce022bb68cae0f952ebbdd048f680f
e61da9a9c2eb2146ace8dc3b37c5e190aa0d1864

I won't argue it's perfect, but I consider it good enough to consider this issue resolved.

Feel free to reopen if there are any specific things you feel are not yet properly separated (it was a huge refactor so I may have missed things).
