### ISSUE TITLE
Pride Flag Doesn't Show Up In Emoji Module

### ISSUE THREAD

**Issue by roseusgarcia** [Pext/Pext#110]
**Describe the bug**
Expected to see the LGBT Pride flag but instead get a different result. Possibly update for the new Unicode?

**To Reproduce**
1. Go to emoji module
2. Search rainbow

**Expected behavior**
Should be able to see the pride flag but instead you get a white flag and rainbow emoji separate
<img width="1552" alt="screen shot 2018-06-03 at 8 15 23 pm" src="https://user-images.githubusercontent.com/37086530/40892895-ef124f3e-676a-11e8-9783-82fdf8b7402d.png">

**Desktop (please complete the following information):**
 - OS: macOS High Sierra 
 - Pext Version 0.14

**Comment by TheLastProject** [comment]
Thank you for the report. Seeing how it does paste it correctly, it seems it's a purely display issue and I'll probably have to look for this in Qt. Not sure where it is wrong though, but I can reproduce it.

**Comment by TheLastProject** [comment]
Fixed in https://github.com/Pext/Pext/commit/c11b205532d0d5922247be03e69b02026c91f8b5.
