### ISSUE TITLE
Emoji Synonyms In Emoji Module

### ISSUE THREAD

**Issue by roseusgarcia** [Pext/Pext#115]
**Is your feature request related to a problem? Please describe.**
So imagine your using the emoji module and you want to use a emoji that shows emotion of happiness. Wouldn't it be a great idea to type "happy" and all the smiley emojis come up or for sad maybe comes all the sad ones? Or even when you type LGBT the pride flag shows up instead of typing rainbow flag. There are endless amounts of examples. 
<img width="1552" alt="screen shot 2018-06-20 at 5 36 32 pm" src="https://user-images.githubusercontent.com/37086530/41686008-840353fc-74b0-11e8-9cc9-4bc92e1e6bee.png">

**Describe the solution you'd like**
By simply typing happy or sad in the search should pop up the appropriate emojis

**Describe alternatives you've considered**
Many software keyboards do this, I believe they used machine learning to determine the right emoji but I think it would make a great addition to the Pext emoji module. It would be much easier to find the right emoji.

Attached is good example where it can bring up the emojis

**Comment by TheLastProject** [comment]
This issue was moved to Pext/pext_module_emoji#4
