### ISSUE TITLE
Pext menu entry shown twice on macOS for most languages

### ISSUE THREAD

**Issue by roseusgarcia** [Pext/Pext#116]
**Describe the bug**
Inconsistent menu labeling when using the Spanish translation. I'm not sure if it applies to the other languages since I don't speak the other languages, but I do know it's happening in the Spanish version.

**To Reproduce**
1. Go to Settings
2. Click on Languages
3. Chose español de España
4.  Let Pext load

**Expected behavior**
Notice I expected it line up with the English version, one thing I noticed is that there's a second tab called Pext and all it does is quit Pext. It doesn't have About Pext which shows the translators and details about Pext obviously.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS High Sierra
 - Pext 0.15

Spanish Version
<img width="1440" alt="screen shot 2018-06-21 at 10 31 30 am" src="https://user-images.githubusercontent.com/37086530/41725672-64afe9b4-753e-11e8-8c29-d0c0b5faf733.png">

English Version
<img width="1440" alt="screen shot 2018-06-21 at 10 34 20 am" src="https://user-images.githubusercontent.com/37086530/41725837-cc87b8e6-753e-11e8-85d3-34a4b9faf1f8.png">

**Comment by roseusgarcia** [comment]
Update: It seems like English and French don't have this issue even though French is missing "About Pext"

**Comment by TheLastProject** [comment]
Should be fixed in bcb49dd0c4edb5d19c549d835d6960346ab8d67b
