### ISSUE TITLE
Woman Facepalm Emoji Doesn't Show Up

### ISSUE THREAD

**Issue by roseusgarcia** [Pext/Pext#121]
**Describe the bug**
When looking for the female facepalm emoji, it gets replaced with the man version and the female symbol

**To Reproduce**
1. Go to the Emoji Module
2. Search facepalm
3. Scroll down to women facepalm
4. And you should see the wrong emoji displayed

**Expected behavior**
Well obviously the female version of facepalm

**Screenshots**
<img width="612" alt="image" src="https://user-images.githubusercontent.com/37086530/42137988-f97ab7c4-7d43-11e8-8573-69d8693302f1.png">

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Pext Version 0.16

**Comment by TheLastProject** [comment]
This issue was moved to Pext/pext_module_emoji#7
