### ISSUE TITLE
Found a joke that you might want to include in Readme

### ISSUE THREAD

**Issue by Omar-Elrefaei** [Pext/Pext#123]
```
"Hey Dad."
"Yes Dave?"
"I've made a Portable."
"A portable what?" asked Dad.
"I dunno, I've only made the handle."
```
Someone wrote this as a comment on the [OMG Ubuntu](https://www.omgubuntu.co.uk/2017/03/pext-python-extendable-tool) article.
Someone should include this in the readme

**Comment by TheLastProject** [comment]
I'm personally not sure about jokes in a README, but maybe it'd be something for the website. A sort of "What people say about Pext" section or so, maybe. I'm labeling this as discussion :)

**Comment by DylanMeeus** [comment]
That does not seem useful for the readme in my opinion.

**Comment by TheLastProject** [comment]
This issue got kinda still and the only responses were "doesn't seem like a good idea", so I'll close it :)
