### ISSUE TITLE
[Windows 10] A fresh install of Pext fails to install modules

### ISSUE THREAD

**Issue by zamber** [Pext/Pext#125]
The bug occurs if Pext is started through the Windows Start Menu shortcut.

**To Reproduce**
1. Start a fresh, module-less installation of Pext through the start menu. 
2. Click on Module > Install module > from online module list
3. Select a module and hit OK
4. See error in a notification and in the bottom status bar of Pext: `'NoneType' object has no attribute 'write'`

**Expected behavior**
Module should install without problems.
After editing the bat that the shortcut runs to run `python` and not `pythonw` everything works as expected.
Wild speculation: something relies on having a handle to the terminal...

**Screenshots**
https://t.me/PextTool/4104
![app_module](https://user-images.githubusercontent.com/557066/44311562-ffda3c80-a3e9-11e8-92cc-0bdfedc1770b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Pext Version: stable v0.17

**Comment by TheLastProject** [comment]
Could you test if https://ci.appveyor.com/api/buildjobs/9n1oahnsv0g64soi/artifacts/Pext.exe works? If it does, it confirms that dulwich/dulwich#658 indeed fixes this.

**Comment by zamber** [comment]
On it...

**Comment by zamber** [comment]
The fix in that build is working fine :). Everything is installing itself properly.

**Comment by TheLastProject** [comment]
Fixed in https://github.com/Pext/Pext/commit/9f5c837b67b050a7289d87db68445665a87a4957.
