### ISSUE TITLE
White background on logo is misaligned

### ISSUE THREAD

**Issue by TheLastProject** [Pext/Pext#137]
<img width="151" alt="screenshot 2018-10-09 at 13 10 41" src="https://user-images.githubusercontent.com/1885159/46681485-9a394e00-cbeb-11e8-891e-d6ddf7603280.png">

This is probably a very easy fix for anyone who has any experience with vector editing software and exporting at all. Either the source is slightly wrong, or the exports went wrong.

Please help :)

**Comment by soulspark666** [comment]
I'll do it!

**Comment by soulspark666** [comment]
Is this the main logo or is it somewhere else, like on a particular page?
Please provide the link to it.

**Comment by TheLastProject** [comment]
It seems to be https://github.com/Pext/Pext/blob/master/pext/images/scalable/pext.svg and various exported versions in https://github.com/Pext/Pext/blob/master/pext/images/. I sadly don't know if the source is wrong or if the exports are, but all the exports seem to have the same issue.

**Comment by soulspark666** [comment]
I have done something #138 , please check if it needs further improvement.

**Comment by soulspark666** [comment]
Please check the changes #139

**Comment by TheLastProject** [comment]
Fixed in https://github.com/Pext/Pext/commit/fa6b0ab0316545421c20b9766a21381c9943f183, thank you so much @soulspark666! Finally Pext's icon looks pretty :)
