### ISSUE TITLE
Window "jumps" back when being dragged on second monitor

### ISSUE THREAD

**Issue by arisboch** [Pext/Pext#151]
**Describe the bug**
When I try to drag the Pext window to my second monitor, it "jumps" back after I let go of it

**To Reproduce**
1) Start Pext
2) Drag the window to the second monitor

**Expected behavior**
Not "jumping" back to the second monitor.

**Desktop (please complete the following information):**
 - OS: Ubuntu MATE 18.10
 - Pext Version: 0.21

**Comment by Gamebase32** [comment]
Reproducable on Ubuntu 18.04 LTS with Gnome.
Pext Version: 0.21 and dev 0.21+11.g23gb7da

**Comment by TheLastProject** [comment]
Thank you for reporting this issue! I've fixed this in https://github.com/Pext/Pext/commit/85380b5c004f395531fcb58ef8e81272145816d2 together with a few other related issues :)
