### ISSUE TITLE
Sorting Options

### ISSUE THREAD

**Issue by VenomousDingo** [Pext/Pext#19]
Options for the sorting menu per module (especially Pass):
Alphanumerical (Ascending/Descending)
By Created (Ascending/Descending)
Last Modified (Ascending/Descending)
Last Used

**Comment by TheLastProject** [comment]
Leaving this as a mental note:

As we discussed in person, I feel it should be implemented roughly in a sorting menu roughly as follows:

**Sorting**
- Module settings
    - Possibly a list here
- Alphanumerical
    - Ascending
    - Descending

Sorting by created/last modified/last used seems like options the module should define, as Pext literally only gets a list of entries and can't know if it's a file or something else altogether. Modules should probably also be able to refuse to sort themselves so only Pext sorting options (alphanumerical) is possible.

Also, to consider: perhaps choosing how to sort commands compared to normal entries.

**Comment by TheLastProject** [comment]
Initial version implemented in d424e2feb561ed7f106f340692960987fbd1ca3f. Leaving it at this for now because the other requests will take way more time. Feel free to re-open if this still feels too limited.
