### ISSUE TITLE
Document OBS packages for other distributions

### ISSUE THREAD

**Issue by TheLastProject** [Pext/Pext#196]
https://github.com/Pext/Pext/blob/master/docs/installation.rst contains instructions for openSUSE, but more repositories are available (despite being untested).

These need to be documented for the relevant distributions:
Stable: https://download.opensuse.org/repositories/home:/TheLastProject:/python-pext/
Nightly: https://download.opensuse.org/repositories/home:/TheLastProject:/python-pext:/devel/

**Comment by jiazheng0609** [comment]
I saw other projects that was also built by Open Build Service would have a "Download package" link on the "Overview" tab, that was linked to https://software.opensuse.org/

For example: [obs-service-recompress project](https://software.opensuse.org//download.html?project=home%3ATheLastProject%3Apython-pext&package=obs-service-recompress)

Not only it has command line instruction for every distribution available, it was also localized into many languages. I guess add a link to this site under Other Distros would be more convenience for both developer and user?

But your main package - python-pext could not be found on this site[[1]](https://software.opensuse.org//download.html?project=home%3ATheLastProject%3Apython-pext&package=python-pext), maybe you could enable it somewhere on Open Build Service?

[1] https://software.opensuse.org//download.html?project=home%3ATheLastProject%3Apython-pext&package=python-pext

**Comment by TheLastProject** [comment]
Oh, such a page would've been great. I've clicked around on OBS, Googled and asked on IRC, but sadly, I can't figure out how to do it :( Worst case scenario we could copy-paste those instructions for this repo and https://github.com/Pext/Website though, I suppose. Thanks for the pointers!

**Comment by TheLastProject** [comment]
I've decided to discontinue OBS due to the lack of interest and the too much work for me to maintain.
