### ISSUE TITLE
Add Arabic Translation

### ISSUE THREAD

**Issue by Raamyy** [Pext/Pext#200]
Add arabic translation in the i11n folder that will help spreading the app <span class="emoji-outer emoji-sizer"><span class="emoji-inner" style="background: url(chrome-extension://immhpnclomdloikkpcefncmfgjbkojmh/emoji-data/sheet_apple_32.png);background-position:59.9882491186839% 65.98119858989423%;background-size:5418.75% 5418.75%" data-codepoints="1f604"></span></span>.

Can I start working on it ?

**Comment by TheLastProject** [comment]
Sure, that'd be awesome! We manage translations through https://hosted.weblate.org/projects/pext/, so please make your translations there.

I assume you want to claim a merge request for Hacktoberfest, so for that, please just add your info to the translator list in https://github.com/Pext/Pext/blob/master/pext/qml/AboutDialog.qml#L31-L43 so you can still get a merge request even though we use Weblate :)

**Comment by Raamyy** [comment]
Okay I will.

But I can't find the arabic language in the language list, How can I add it ?

**Comment by TheLastProject** [comment]
If you log into Weblate and then choose a component (like https://hosted.weblate.org/projects/pext/pext/, which is the main project), you should be able to click a "Start new translation" button at the bottom of the page.

**Comment by TheLastProject** [comment]
Going to close this issue to keep the issue tracker clean, feel free to reopen if you have more questions and thanks for your work so far :)

**Comment by TheLastProject** [comment]
Hey, just want to say that if you want Arabic to actually be included, you'll have to translate a bit more than 15%. If not, hopefully someone else will pick up the rest some day :)
