### ISSUE TITLE
Prepare for 0.9 release

### ISSUE THREAD

**Issue by TheLastProject** [Pext/Pext#21]
A lot of things have improved since 0.8, so it seems time for a new release again

- Ensure translations are up-to-date:
  - [x] Dutch
  - [x] Spanish
  - [x] Traditional Chinese
- [x] Make sure there are no blockers or serious regressions (did you notice anything? Please report quickly!)

**Comment by s8321414** [comment]
zh_TW translation is done now 😄

**Comment by TheLastProject** [comment]
And released, thanks for all the help @Pext/translators! :)
