### ISSUE TITLE
Linux Packaging

### ISSUE THREAD

**Issue by TheLastProject** [Pext/Pext#22]
Packaging Pext a bit better would be nice. It can already be installed under Linux just fine using setup.py, but on macOS, that support is very lacking. macOS support or maybe an AppImage or Snap or so would be awesome.

Edit: If you're here for Hacktoberfest, support for a single of the following formats would suffice:
macOS App
AppImage
Snap
Flatpak
Deb
RPM

Edit 2: title changed to Linux packaging because that's what's being done.

**Comment by TheAssassin** [comment]
I might give an AppImage a try, mostly to improve our docs on packaging Python applications. You mentioned issues you experienced while packaging Pext using some of the Python tools. Could you elaborate a bit?

**Comment by TheLastProject** [comment]
I never really managed to put time in AppImage. My issue with packaging Pext was mostly py2app not being able to create proper builds that can be installed as a .App, instead of only running in-place with the git repository still there.

**Comment by TheLastProject** [comment]
Note to self for things I need to do for @TheAssassin's AppImage:
- Replace git subprocess calls with Pygit2 because libgit is easier to package
- Make notify-send optional, preferably replace completely.
- Get a list of files currently in the built AppImage that can be removed to lower filesize (use ```strace AppRun``` to make sure nothing of the local filesystem is called, to make sure everything is self-contained).

**Comment by TheAssassin** [comment]
Also, call `strace` on the final AppImage (as root, otherwise it won't work) and look for resources loaded from the host by calling the following script ([source](https://github.com/AppImage/AppImageKit/wiki/Bundling-Python-apps)):

```
strace -eopen -f ./pext-x86_64.AppImage 2>&1 | grep / | grep -v ENOENT | cut -d "\"" -f 2 | sort | uniq
```
