### ISSUE TITLE
Installing on Windows 10 doesn't create a shortcut

### ISSUE THREAD

**Issue by TangentFoxy** [Pext/Pext#220]
It looks like it is intended for there to [be a shortcut](https://github.com/Pext/Pext/blob/master/.appveyor.yml#L40) created by the NSIS installer.. This did not get created.

- OS: Windows 10
- Pext v0.26-27-g044fc99

**Comment by TheLastProject** [comment]
Interesting. I wonder if this may be a quoting issue and could be as easy to fix as #217.

**Comment by TangentFoxy** [comment]
[Reference](https://nsis.sourceforge.io/Reference/CreateShortCut) shows an example with double quotes. How would I go about testing this before submitting a pull?

**Comment by TangentFoxy** [comment]
The issue isn't with that line, it's that because the installer is running as an administrator, it is installing the shortcut there instead of for the current user:

![image](https://user-images.githubusercontent.com/15093567/67643729-c9465e80-f8d7-11e9-8161-1e65cd16a394.png)

**Comment by TangentFoxy** [comment]
So the simple solution is to use [SetShellVarContext](https://nsis.sourceforge.io/Docs/Chapter4.html#setshellvarcontext) and install for all users, instead of installing only for the administrator account.

The complex solution is to use the [UAC plugin](https://nsis.sourceforge.io/mediawiki/index.php?title=UAC_plug-in&oldid=19055), which requires a lot of change of the .NSI file. This is the only way to allow a non-administrator user to possibly install Pext for only themselves.

**Comment by TangentFoxy** [comment]
[A third solution](http://drizin.io/NSIS-and-Windows-Installers-for-MultiUser-Current-User/) has been discovered which would change Pext to be installed to a user's directory instead of in the system's program files.

**Comment by TheLastProject** [comment]
Fixed in #222
