### ISSUE TITLE
launcher: Exception thrown: replace_command_info_dict

### ISSUE THREAD

**Issue by siriobalmelli** [Pext/Pext#23]
Opening a tab with launcher fails (immediately closes the tab) and gives this error message in the bottom of the window:
`launcher: Exception thrown: replace_command_info_dict`

in the underlying console, Pext gives:
`WARN: Module pass uses old process_response signature and will not be able to receive an identifier if requested`

System info:
```.bash
$ uname -a
Darwin [hostname] 15.6.0 Darwin Kernel Version 15.6.0: Tue Apr 11 16:00:51 PDT 2017; root:xnu-3248.60.11.5.3~1/RELEASE_X86_64 x86_64
$ python3 --version
Python 3.5.3
$ 
```

Any info is appreciated, thank you.

**Comment by TheLastProject** [comment]
I accidentally forgot an API version check in pext_module_launcher (I constantly use the latest master), causing it to try to call functionality not available in Pext 0.9. I fixed it in https://github.com/Pext/pext_module_launcher/commit/f5a7b95ad187eb8d128ca32d77373f5922d7360e. Just update your copy of the launcher module and it should work. Thanks for reporting!
