### ISSUE TITLE
Test Windows support

### ISSUE THREAD

**Issue by TheLastProject** [Pext/Pext#24]
Pext should probably mostly run on Windows (Python 3 + Qt5), but this has never been tested as I do not own a Windows machine. Getting the core to start on Windows with instructions would be great. It is acceptable if it does not install modules yet or crashes when trying to send a notification, as those are still hardcoded to notify-send and "git". It is also acceptable if this uses WSL, although the more "native" the better.

So, to summarize:
- Test if Pext can run under Windows
- Write instructions for the README on how to do so
- Document what works and what doesn't work yet

As I may not be able to have access to a Windows machine to verify your work (although I will try!), please add a video or screenshots as proof if possible. The main need is to make sure Pext at least launches on Windows, to hopefully invite further collaboration to ensure ongoing Windows compatibility, either by you or someone else.

**Comment by step21** [comment]
I could test this if you like.

**Comment by TheLastProject** [comment]
That would be great! Do you have any experience on making Python applications with PyQt run on Windows? I personally haven't used Windows in years, so I can't really do anything more than guess.

**Comment by step21** [comment]
I have lots of experience with making almost anything run on windows, particularly python. Often because I dual booted for various reasons and wanted to try some software but was too lazy or unable to reboot. I do not have particular experience with pyqt but I don't think that should be a problem.

**Comment by TheLastProject** [comment]
Awesome, let me know if you need anything or run into problems!

If you'd prefer IRC over GitHub issues, feel free to join #pext on OFTC IRC or poke me directly on either OFTC or Freenode (SylvieLorxu is my nick there). Otherwise I'll assume to hear from you on here :)

**Comment by step21** [comment]
I think here is fine for now, have to fix my irc setup.
First issue I ran into - when you're handling the pid file, the path for that is hardcoded as `/tmp/pext_{}.pid` which is a problem. On most Windows installs this does not exist (and that is where it currently fails for me), resulting in a FileNotFoundError. When using bash (not WSL) sometimes you can use things like `/c/...` but that does not seem to work for python and while bash handles `/tmp` (which it puts into its program directory) this does not translate to python.
If I try that code manually with a Windows path, it works though. So something like `C:\Users\User\pidfile` though if you would do it for example in `C:\tmp` then you would get a PermissionError as well unless you are running the process with elevated priviliges. I think the right path would be `C:\\Windows\Temp` where also users can write. I think maybe it could also make sense to check how other programs do it, like Mailpile for example.

**Comment by step21** [comment]
It does seem to use some kind of vfs system, but for local files it just passes through the arguments from what I can tell.

**Comment by TheLastProject** [comment]
The path thing seems like an easy fix by simply using [tempfile.gettempdir()](https://docs.python.org/3/library/tempfile.html?highlight=tempfile#tempfile.gettempdir). While at that the ConfigRetriever class should probably also stop solely using XDG_CONFIG_HOME, but that seems like a very minor issue. I assume it is most convenient if I leave that change to you 

If I understand your message correctly, with that fix applied, it at least starts up correctly, GUI and all? Because that's a rather neat start!

I'm in the process of replacing the direct calls to git with [pygit2](http://www.pygit2.org/) because of #22, which should make installing modules and themes work on Windows as well, at which point we'll have to see if the modules can be loaded and run at all. If you want to look into modules being able to load at all, you could already ```git clone https://github.com/Pext/pext_module_openweathermap``` into ~/.config/pext/modules/pext_module_openweathermap manually and see if Pext can load and run that module. That module seems the best one to start with because it doesn't require any dependencies.

On the note of module dependencies, I assume https://github.com/Pext/Pext/blob/master/pext/pext.py#L723-L771 will be a problem in the installation step as well? Of course, we can also simply see if it happens to work or not after I make the pygit2 changes.

**Comment by step21** [comment]
No, doesn't start up yet. But that might only be because I accidentally installed Python 3.4 which is not supported anymore from what I understand because of commonpath, but installing a new version and getting the PATH right sometimes takes some time in Windows. I used os.name to set two different paths if that is 'nt' but maybe the tempdir is better, yeah. Git should not be a problem, at least for me as it is in my PATH. Not sure if installing with pip would be a problem.

**Comment by TheLastProject** [comment]
According to https://docs.python.org/3/whatsnew/3.4.html#whatsnew-pep-453, Python 3.4 includes pip, even on Windows. I'm mostly wondering if it'll work as-is. But I suppose the best way to figure out is to just try to see.

Looking at the wheel for pygit2, it seems to come with a git2.dll, which I'd assume is libgit2, so hopefully that'll work out of the box on Windows after a pip install. I say hopefully because documentation on pygit2 doesn't clearly state this.

Also, thanks for the note on commonpath. It's rather hard to tell what version of Python what functions were introduced in. That code may disappear with the pygit2 migration. But yeah, as is, 3.4 indeed won't work.

**Comment by step21** [comment]
Yes, pip is always included. Just didn't test it yet.
So now it starts (shows the Window) but immediately crashes on `signal.SIGUSR1` I think this is just not available on Windows, python reference says this "Note that not all systems define the same set of signal names; only those names defined by the system are defined by this module."

**Comment by step21** [comment]
Installing with pip works.

**Comment by step21** [comment]
XDG_CONFIG_HOME is not used, but the exception block with `os.path.expanduser('~/.config')` works correctly.

**Comment by TheLastProject** [comment]
I just finished the migration from git to pygit2. Thanks for your testing. The signal.SIGUSR1 is used as a custom signal to reopen the running Pext instance if you launch Pext while it is already running. The signal is used to "poke" Pext to show itself if it's already running. I'm not sure how to best do this under Windows, that will require some additional research. Until we find a fix for that, it's probably best to just comment out the "Handle SIGUSR1 UNIX signal" part, but this will need fixing, so that we don't end up with 2 instances on one profile overwriting each other's settings.

Glad to hear about the progress though, sounds like we're rather close to a pull request with "experimental" Windows installation instructions for the README? :)

**Comment by step21** [comment]
Sure, I can write something up. For custom signals/ipc I think there is things like pipes, mzq or sockets. If it is just about bringing the window to the foreground, I believe you can set the window state which python supports. Such as here: https://docs.python.org/3/library/subprocess.html#subprocess.STARTUPINFO https://msdn.microsoft.com/en-us/library/ms633548(v=vs.85).aspx

**Comment by TheLastProject** [comment]
Closed by #29 and #30. Still space for improvement, of course (fixing the small missing feature as described above and making a .exe or installer or so) but for now, Windows compatibility is there :)
