### ISSUE TITLE
CI support

### ISSUE THREAD

**Issue by TheLastProject** [Pext/Pext#25]
Pext is long overdue on some CI. Travis is probably the most logical choice. Making sure Pext runs and the (code standard) tests are run would be the scope of this issue. Unfortunately we lack other unit tests.

**Comment by arpitx165** [comment]
Can you tell me what is required packages in order to run the application?If Any other dependency related to python version?Let me know

**Comment by TheLastProject** [comment]
The dependencies are listed on https://github.com/Pext/Pext#dependencies. The Python version has never properly been tested aside from "Python 3", so the supported Python 3 versions would be something to test with CI. @TheAssassin is currently messaging me on IRC asking questions on Travis as well, so I believe he started working on this as well (probably in relation to #22), so this issue may be "stolen away" I'm afraid.

**Comment by TheLastProject** [comment]
Well, the macOS build runs on Travis and executes Tox tests, so I'll close this as "good enough".
