### ISSUE TITLE
Preparing for 1.0

### ISSUE THREAD

**Issue by TheLastProject** [Pext/Pext#32]
Pext has gotten rather far and stable, so it's about time for a 1.0 release.

Checklist of things that should be supported before it:
- [ ] Internationalisation support for module metadata
- [x] Moving selection_made calls into a thread so modules can't lock the UI up there (be very careful here to not break anything!) dd4056bff397cc79044e372a8816f7e0ce3649a9
- [ ] Ensure the API can't crash Pext with bad input
- [x] Update checking for Pext itself, at least to notify about new versions (possibly disable in AppImage due to native support) 0fcd40a46e07759885b706a518e66ef2aa981443

Great to have before the release but not required:
- [ ] AppImage (see #31)
- [ ] Working macOS .app (see #27)
- [ ] Windows installer

- [ ] Automatic module updates (on/off for checking and auto-updating in UI)

When all of the above (aside perhaps the great to haves) are done:
- [ ] Translations 100% (not required)

**Comment by TheAssassin** [comment]
I'm sure we'll be able to release AppImages soon.

**Comment by TheLastProject** [comment]
Looks like I'll be releasing a v0.10 before this, as I found a few major bugs. v1.0 will probably then focus on finishing the last lacking bit of localization and packaging for all platforms.

**Comment by TheLastProject** [comment]
On that note, @Pext/translators, seeing how v0.10 may drop in the coming days, this is the time to update your translations if you get the chance.

**Comment by TheLastProject** [comment]
This got split into one issue per thing, going to close this now for organisational reasons.
