### ISSUE TITLE
Modules failing to install on Debian Buster

### ISSUE THREAD

**Issue by wodend** [Pext/Pext#322]
**Describe the bug**
pip fails to install modules in Debian Buster with the `--system` flag.

**To Reproduce**
1. Go to Module > Install module > From online list
2. Click Ok (This affects all module installs)

**Expected behavior**
Module installs successfully.

**Screenshots**
pip throws an error when trying to combine `--target` and `--system` flags and module fails to install.

**Desktop (please complete the following information):**
 - OS: Debian Buster
 - Pext v0.31-13-g948919a

**Additional context**
I am not running venv, or using another Python environment manager such as Conda.

Debian buster __/etc/issue.net__:

```
Debian GNU/Linux 10
```

**Comment by wodend** [comment]
Link from Matrix discussion:

https://github.com/pypa/pip/issues/3826

**Comment by TheLastProject** [comment]
Thanks for the report and providing your /etc/issue! This should be fixed in 5dbaad52626c8497dc1417fe43b58e8813ee5d41
