### ISSUE TITLE
pygit2 doesn't support HTTPS on Debian

### ISSUE THREAD

**Issue by TheLastProject** [Pext/Pext#35]
Well, this is extremely annoying, guess installing AND updating Pext modules is now broken on Debian.

https://github.com/libgit2/pygit2/issues/644

Upstream bugs:
https://bugs.launchpad.net/ubuntu/+source/libgit2/+bug/1595565
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=832798

This manifests in the following error:
```_pygit2.GitError: Failed to resolve address for https: Name or service not known```

**Comment by TheLastProject** [comment]
Planned workaround for now:

Use ``bool(pygit2.features & pygit2.GIT_FEATURE_HTTPS)`` and ``bool(pygit2.features & pygit2.GIT_FEATURE_SSH)`` or ``if 'ssh' in pygit2.features`` and ``if 'http' in pygit2.features`` to check what type of URLs are supported and ensure the UI won't recommend unsupported URLs.

**Comment by TheAssassin** [comment]
We can probably continue to build our own libgit2 (up to date and with patches) for the AppImage releases. But that PR will have to wait for my cURL packages to be finished.

**Comment by TheAssassin** [comment]
I'd suggest to change the title like `s/pygit2/libgit2/`, as this is not an issue with pygit2 but its main dependency, and also not directly libgit2 but the version Debian/Ubuntu ship.

**Comment by TheAssassin** [comment]
Did you check whether the bug persists with older/newer versions of libgit2/pygit2? We are not really bound to a specific version here, the required functionality (clone/pull) should be available in all releases.

**Comment by TheLastProject** [comment]
After more research, it was decided to switch to Dulwich instead. This migration is almost complete, just need to find a way to implement "git describe" in it

**Comment by TheLastProject** [comment]
Fixed in 0c3cdcae4ee5601507e62d738cd9adfe64f918e9.

**Comment by TheAssassin** [comment]
Awesome news. I'll try to find some time to work and hopefully finish the AppImage build processes. This feature has been worked on for long enough in my opinion, and I hope we can get it work in 2017.
