### ISSUE TITLE
newer version 0.6 ?

### ISSUE THREAD

**Issue by tissatussa** [Pext/Pext#405]
on the webpage https://www.omgubuntu.co.uk/2017/03/pext-python-extendable-tool i read about version 0.6 !? ::

The developer of Pext very kindly sent me an email to let me know that Pext 0.6 is now available to download, adding that “…the app is actually reaching the point where it’s actually usable for users, having gotten a lot of improvements to its user-friendliness and having had some major bugs fixed.“

does it mean a fork of Pext ?  Is "0.6" a typo in this article ?

**Comment by TheLastProject** [comment]
Nope, the article is just very old :) Back when it was written, Pext 0.6 was the latest version available. Currently, the latest version available is 0.32: https://github.com/Pext/Pext/releases.

See https://pext.readthedocs.io/en/latest/installation.html for installation instructions :)
