### ISSUE TITLE
Automatic module updates

### ISSUE THREAD

**Issue by TheLastProject** [Pext/Pext#44]
This would be useful, of course with user permission. It's easy to forget updates if you always have to check manually

**Comment by vanyasem** [comment]
Not really related to the issue, but that would be nice to support manually installed modules. I will be able to package modules in AUR (Arch User Repository) then. Providing a seamless experience updating modules on Arch.

**Comment by TheLastProject** [comment]
I agree, but I'm not quite sure how to support this in Pext. I suppose just try to prefer a system directory to load from if it exists? How would Pext know which directory it should try? How would distro maintainers prefer to set this?

**Comment by TheLastProject** [comment]
Fixed in https://github.com/Pext/Pext/commit/669305a26092538a98410bb08ad547c3da230375.
