### ISSUE TITLE
Pext-git is not working in Arch Linux installed from AUR.

### ISSUE THREAD

**Issue by airvzxf** [Pext/Pext#476]
I installed `pext-git` from the AUR repository in Arch Linux, but it is failing in the installation, as I showed in the screenshots below.

**To Reproduce**
1. Open a terminal.
2. `yay -S pext-git`

**Expected behavior**
Complete the installation.

**Screenshots**
![image](https://user-images.githubusercontent.com/831380/196057689-0a2c8098-9884-4dc8-af31-4f20f4653c81.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux: Linux 6.0.1-arch2-1 # 1 SMP PREEMPT_DYNAMIC Thu, 13 Oct 2022 18:58:49 +0000 x86_64 GNU/Linux
 - Pext version [check About screen or run Pext with --version]: N/A
 - Module version (if applicable) [Module -> manage modules -> Version]: N/A
 - Python version: Python 3.10.8

**Quick Note:**
Could you add the labels "hacktoberfest and hacktoberfest-accept" to this issue?

**Additional context**
```
                   -`
                  .o+`                 wolf@MSIGT73EVR7RF
                 `ooo/                 OS: Arch Linux
                `+oooo:                Kernel: x86_64 Linux 6.0.1-arch2-1
               `+oooooo:               Uptime: 5h 3m
               -+oooooo+:              Packages: 1600
             `/:-:++oooo+:             Shell: zsh 5.9
            `/++++/+++++++:            Resolution: 3840x1080
           `/++++++++++++++:           WM: OpenBox
          `/+++ooooooooooooo/`         WM Theme: Clearlooks
         ./ooosssso++osssssso+`        GTK Theme: Adwaita [GTK3]
        .oossssso-````/ossssss+`       Disk: 353G / 469G (79%)
       -osssssso.      :ssssssso.      CPU: Intel Core i7-7820HK @ 8x 3.9GHz [51.0°C]
      :osssssss/        osssso+++.     GPU: NVIDIA GeForce GTX 1080
     /ossssssss/        +ssssooo/-     RAM: 5247MiB / 64269MiB
   `/ossssso+/:-        -:/+osssso+-
  `+sso+:-`                 `.-/+oso:
 `++:.                           `-/+/
 .`                                 `/
```

**Comment by TheLastProject** [comment]
This doesn't look like a Pext issue, but like a network issue on your side? Given it says it's failing to connect to github.com?

> Could you add the labels "hacktoberfest and hacktoberfest-accept" to this issue?

That's not how Hacktoberfest works, it works on PRs, not on issues, so that wouldn't change anything.

**Comment by airvzxf** [comment]
Confirmed, it is working.
I ran `yay -S pext-git` and this is the result.

![Screenshot_2022-12-08_09-49-06](https://user-images.githubusercontent.com/831380/206493801-4ce47049-b3a9-4f7b-a1bd-52c9cd0370a8.png)
