### ISSUE TITLE
Pext should help users install dependencies

### ISSUE THREAD

**Issue by Canuteson** [Pext/Pext#5]
Either for running directly, a way to manage dependencies should be a minimum requirement for a software distribution like this.

**Comment by TheLastProject** [comment]
This is indeed a point that definitely needs to be addressed.

Quoting from #6:
>This doesn't address the missing dependencies in the core modules you've created. Short list:
>
>    pext_module_pass ** pexpect ** pyinotify
>    pext_module_emoji ** emoji
>
>Not sure how to address that. A couple of options:
>1. Give the core modules installers and let people install them via Pip, then update the ModuleManager to search the global namespace for Pext Modules.
>2. update the Module installer to actually install the modules as Python libraries. This would probably fail if the user is not running Pext in a virtualenv or as root(!)
>3. Add the dependencies of the core modules to the dependency list of Pext itself (kind of ugly)
>4. ???

3 is obviously not scalable, as it will actively require third-party developers to convince me to make their dependency a dependency of Pext, regardless of if people would actually want to use the module in question.

It seems reasonable to let Pext use pip to install, which would allow supporting PyPI and allow other popular version control systems to be used too.

Note to self: Look into `--target` and how upgrading works and how to allow the user to choose between the latest release and development versions (would this be a simple branch switching thing on Git?)

Again, as this is a packaging thing, I'd like to hear your two cents if you have some time, @jhdulaney.

**Comment by TheLastProject** [comment]
This should be fixed in 4a27bca07d8fc472662cdcd618536f4522a8c357. Hopefully we can one day switch to a virtualenv to ensure that different Pext modules can use different module versions, but for now, this should work well.
