### ISSUE TITLE
python-dulwich from AUR provides dulwich for Python2

### ISSUE THREAD

**Issue by vanyasem** [Pext/Pext#56]
Pext is written in Python3 so it needs `dulwich` for Python3. Unfortunately, both `python-dulwich` packages from AUR contain dulwich for Python2

You could just install it from PyPi using `pip3 install dulwich --user`

**Comment by TheLastProject** [comment]
Fixed in f83f5e78f20ab3db484f7c5b9475c765f93aaef8, thanks!
