### ISSUE TITLE
Pext logo doesn't have good textual contrast with (at least some) dark themes

### ISSUE THREAD

**Issue by kozross** [Pext/Pext#58]
### Is this a bug or a feature request?

Bug.

### What Pext version are you running?

Pext v0.11.1-19-g4ca9d49 (according to ``pext --version``)

### What OS are you using? (e.g.: Ubuntu 16.04, Windows 10, macOS High Sierra)

Arch Linux, with KDE as my DE.

##### What did you do to run into this bug, step-by-step?

Open Pext and looked at the logo with KDE's Breeze Dark theme.

##### What did you expect would happen?

The logo wouldn't look bad.

##### What actually happened?

Black text of 'Pext' on a dark grey background lacks contrast and looks bad. 
![Evidence of appearance](https://user-images.githubusercontent.com/8463904/34457987-0103a610-ee27-11e7-837b-000d0e3b6567.png)

### Is there anything else you would like to add?

I think having a dark-theme-friendly logo would be ideal. While I understand dark theme detection isn't easy or even possible, this would be a great UI improvement.

**Comment by TheLastProject** [comment]
Fixed by @VenomousDingo in 4c03f8b210661d9aad86cb118a9c2f9d3f3a94ef and b8244a6dbff54923603916a026082b960775a5aa
