### ISSUE TITLE
Radiobrowser renders text in different sizes

### ISSUE THREAD

**Issue by kozross** [Pext/Pext#59]
### Is this a bug or a feature request?

Bug.

### What Pext version are you running?

Pext v0.11.1-19-g4ca9d49 (according to ``pext --version``)

### What OS are you using? (e.g.: Ubuntu 16.04, Windows 10, macOS High Sierra)

Arch Linux, with KDE.

##### What did you do to run into this bug, step-by-step?

1. Start Pext's radiobrowser module
2. Choose 'By Most Tune-Ins'
3. Wait for the station list
4. Hover over one

##### What did you expect would happen?

The text in each of the three segments to be consistent.

##### What actually happened?

![pext-radiobrowser-text-wtf](https://user-images.githubusercontent.com/8463904/34458015-07eeecc2-ee28-11e7-81dc-5a0c71e21017.png)

### Is there anything else you would like to add?

This is a UI quibble, but it seems odd.

**Comment by TheLastProject** [comment]
Should be fixed in db3a393c3b5b1686db4e026335c08cb4fe23e578.
