### ISSUE TITLE
Radiobrowser gives weird terminal dump without a force unload or crash

### ISSUE THREAD

**Issue by kozross** [Pext/Pext#60]
### Is this a bug or a feature request?

Bug.

### What Pext version are you running?

Pext v0.11.1-19-g4ca9d49 (according to ``pext --version``)

### What OS are you using? (e.g.: Ubuntu 16.04, Windows 10, macOS High Sierra)

Arch Linux.

##### What did you do to run into this bug, step-by-step?

1. Start Pext in the terminal and load radiobrowser
1. Start some music playin'
1. Go to 'By Most Tune-Ins' (I think - I don't exactly recall what triggered this)
1. Observe this lovely dump in your terminal

```
[koz@Sebastian ~]$ pext
python3-opengl is not installed. If Pext fails to render, please try installing it. See https://github.com/Pext/Pext/issues/11.
Using locale: en_NZ 
Localization loaded: True
python3-opengl is not installed. If Pext fails to render, please try installing it. See https://github.com/Pext/Pext/issues/11.
Using locale: en_NZ 
Localization loaded: True
WARN: Module radiobrowser uses old process_response signature and will not be able to receive an identifier if requested
WARN: Module radiobrowser caused exception list index out of range
Counting objects: 59, done.
Total 59 (delta 0), reused 0 (delta 0), pack-reused 59
Checking out HEAD
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pext/__main__.py", line 593, in run
    self._process_tab_action(tab, active_tab)
  File "/usr/lib/python3.6/site-packages/pext/__main__.py", line 554, in _process_tab_action
    tab['vm'].context_menu_base = action[1]
IndexError: list index out of range
```

This did _not_ force a module unload or crash Pext - music kept playing.

##### What did you expect would happen?

Terminal spew not occur, especially indicating out-of-range issues.

##### What actually happened?

See note above.

### Is there anything else you would like to add?

No.

**Comment by TheLastProject** [comment]
Should've been fixed in dc9622d44a36bfb7b922e3a24f1845f0e142936b
