### ISSUE TITLE
Documentation license?

### ISSUE THREAD

**Issue by kozross** [Pext/Pext#66]
Is the documentation licensed the same way as Pext itself (GPL-3.0+)?

**Comment by TheLastProject** [comment]
As it's in the same repository, I do consider it this way. However, now that you say it, for documentation another license may make more sense, as the GPLv3+ isn't really meant as a documentation license?

**Comment by kozross** [comment]
GPL3+ is possible to use for this. The main difficulty lies in the source provision clause, as it would require the docs to be shipped in source form, or at least be made available in such, where 'source' is the format most amenable to changes. We can use CC-BY-SA-4.0 instead if you think that would be better, which avoids these issues while still being copyleft. I'm happy with either option.

**Comment by step21** [comment]
The docs are shipped in 'source form' anyway, so it shouldn't matter and even otherwise it is really a non issue as far as I know. Still, I don't care if the license is changed on the docs.

**Comment by TheLastProject** [comment]
This is fixed with the merging of #67, just forgot to close it. Will do so now.
