### ISSUE TITLE
Pext 'news' needs to exist

### ISSUE THREAD

**Issue by kozross** [Pext/Pext#69]
This is in reference to #68, specifically the following from @VenomousDingo:

"I agree that there should be an update/announcement blog, yes. Like a Twitter account that can post commits or even be used as a "support chat" of sorts if someone can't access IRC."

(Yes, I can't link to those properly, sue me, I prefer CLIs for a reason)

I would be happy to operate such a service or set of services, but I believe we first have to decide how this will work.

**Comment by TheLastProject** [comment]
I agree with this. I'd rather operate it myself, to stay in more control, but I definitely agree there should be something like this.

I wonder if there's a blogging platform (maybe WordPress?) that can post blog entries to Twitter as well, so we can have both a blog and a Twitter account for Pext? Can GNUSocial/whatever users subscribe to the blog RSS perhaps?

**Comment by kozross** [comment]
I know that a Twitter/GNUSocial bridge exists, but I've found it lacklustre. I've not considered blog -> Twitter solutions, so I'm not sure what exists in that space. I believe a Twitter account for Pext is a good idea, but given how that platform tends to operate, having a CoC is pretty essential before we start there.

If you have a blog with RSS, then subscribing/following isn't the issue. Something like Twitter/GSocial/whatever is more for @VenomousDingo's second point (regarding a 'support chat' for those who can't access IRC).

**Comment by TheLastProject** [comment]
I made https://twitter.com/PextTool as a start. That could be some place to receive news on. I'll add it to the site in a nice way later.

**Comment by TheLastProject** [comment]
I would say this is fixed with 0986ab473154fcdc37bfb86911042561315b1211. Twitter is also synced with the IRC channel. Improvements of course welcome, but this seems to fix this for the time being at least.
