### ISSUE TITLE
Weird Window Resizing Issue

### ISSUE THREAD

**Issue by henleygarcia** [Pext/Pext#77]
So it seems like when you resize the window into a smaller frame this just happens. 
![capture](https://user-images.githubusercontent.com/11667696/36948943-f0ecbdba-1faf-11e8-83e7-8b55cceba672.PNG)

**Comment by TheLastProject** [comment]
Pext definitely should have some minimum size set, so you can't resize it that ridiculously. Thanks for reporting!

**Comment by roseusgarcia** [comment]
This seems to happen in macOS as well, not only Windows.

**Comment by TheLastProject** [comment]
Fixed in f64142e046dfe4eef0f4006dce67f35e8f91ef6a.
