### ISSUE TITLE
Theming Issues on Windows 10

### ISSUE THREAD

**Issue by henleygarcia** [Pext/Pext#78]
The example shown below is on Windows 10 using the Gun Metal Theme. I tried others and it seems to have similar results.

![capture](https://user-images.githubusercontent.com/11667696/36949664-b84d52a8-1fb9-11e8-8e40-92a7e0e05ccb.PNG)

**Comment by TheLastProject** [comment]
For comparison, this is how gunmetal looks on Linux, and is supposed to look:
![photo_2018-03-04_20-40-15](https://user-images.githubusercontent.com/1885159/36949700-44da507c-1fec-11e8-957a-c4ca5042226e.jpg)

I'm not sure what's wrong with the Windows theming, but this is definitely something that I'll have to look into (or someone who is more experienced with Windows).

**Comment by TheLastProject** [comment]
Some research and testing showed this is because of Qt defaulting to the windowsvista style. Running Pext with --style=Fusion greatly improves this. I will soon patch Pext to default to Fusion if a theme is enabled

**Comment by TheLastProject** [comment]
Fixed in ac68b75650029d369007130f448ddb7954641263 by forcing Fusion styling on Windows if a theme is selected.
