### ISSUE TITLE
Paste to an active text field

### ISSUE THREAD

**Issue by vanyasem** [Pext/Pext#80]
It's a feature request. Pext should have an option to automatically paste copied text to an active text field

##### What did you do to run into this bug, step-by-step?
1. Open Pext with emoji module
2. Select an emoji

##### What did you expect would happen?
Pext copies the emoji and pastes it into an active text field (Riot Desktop in my case)

##### What actually happened?
Pext just copied the emoji

It would be nice to get this implemented as a Pext setting globally for all modules (pass, emoji, etc)

**Comment by TheLastProject** [comment]
I'm working on this in the https://github.com/Pext/Pext/tree/feature/typeOutput branch.

Needs the new pypi package "pynput".

Current build output:
https://transfer.sh/uU7wg/Pext-x86_64.AppImage
https://transfer.sh/CqcO4/Pext.dmg

I'm going to need to test this on a few more systems to ensure it works before I move this to master.

**Comment by TheLastProject** [comment]
To test, you have to manually change the output location in the Settings menu. I think the naming of the options needs changing too, but not sure how to phrase it atm.

**Comment by vanyasem** [comment]
[python-pynput](https://aur.archlinux.org/packages/python-pynput/) is packaged for Arch in AUR

**Comment by TheLastProject** [comment]
I merged this into master and consider this to be working.

**Comment by TheLastProject** [comment]
Pext sometimes types before the other window is really active, causing one or more of the characters at the start to get lost. Reopening until that's fixed.

**Comment by TheLastProject** [comment]
"Fixed" in 0a1c521a6b87e8aada17d8b953f2ac974e3cd332.
