### ISSUE TITLE
SSL Error in git when attempting to install modules

### ISSUE THREAD

**Issue by roseusgarcia** [Pext/Pext#82]
Thank you for reporting a bug or requesting a feature. Please try to answer as many of the questions below as you can. It is okay if you cannot answer everything; we still appreciate your report very much.

### Is this a bug or a feature request?
Bug.

### What Pext version are you running? (the output of ``pext --version``)
0.12 (I am using the dmg that is being worked on).

### What OS are you using? (e.g.: Ubuntu 16.04, Windows 10, macOS High Sierra)
macOS High Sierra

##### What did you do to run into this bug, step-by-step?
Launched Pext, went to install module, clicked on emoji and then got this message.
##### What did you expect would happen?
I expected that the emoji module or the openweathermap module to load after clicking them to install
##### What actually happened?
It didn't load the desired module and gave me a message on the bottom part of the window. Attached is a screenshot of what the error gave me.

<img width="1551" alt="screen shot 2018-03-21 at 1 01 12 pm" src="https://user-images.githubusercontent.com/37086530/37725023-5c7c305a-2d08-11e8-8fbe-b453aa371f9b.png">

**Comment by TheLastProject** [comment]
I have attempted to fix this in 0de2f409e5fa37609db7358eee2fda03d0e13145. A new build will be available on https://travis-ci.org/Pext/Pext/builds/356508880 whenever the Travis backlog clears (will probably take some hours). I'll try the build myself tomorrow.

**Comment by TheLastProject** [comment]
Fixed in 2d968fab254476214755d09af94107935fd64598 and 9a1146801f131f214c99b0adc9afc001c8ad70b9 for the other install issue that showed up.
