### ISSUE TITLE
prioritize history

### ISSUE THREAD

**Issue by anarcat** [Pext/Pext#9]
it would be nice if pext would list first commands that were already ran. this is what tools like rofi do and make them super useful...

**Comment by TheLastProject** [comment]
Are there any modules you mostly want this behaviour in? I think it's probably better for modules to do this themselves as modules may want to display the entries and commands in a certain order and I'd prefer Pext itself to make as little assumptions about the modules themselves as possible to give module developers as much freedom as they could possibly need. Pext should, however, provide some easy way to persist data between sessions to make it easier for modules to store this ordering (the pass module already sorts using the "last read" date of the files, but not all distributions have this function enabled).

**Comment by TheLastProject** [comment]
Going to close this as I did not get further info and have no reason to believe this should be dealt with in Pext's core as opposed to in a module.
