### ISSUE TITLE
Pext name is not translatable in title and tray

### ISSUE THREAD

**Issue by TheLastProject** [Pext/Pext#92]
This is not a problem in most languages, but in for example Hindi, one should avoid English characters.

**Comment by theimpulson** [comment]
I don't get it. Does that means that We should have **Pext** rather ** पैक्स्ट ** ?

**Comment by TheLastProject** [comment]
Fixed in https://github.com/Pext/Pext/commit/7a2a618f47a26395287faf8a45e6593c4222038f, will need #54 fixed to be truly consistently translatable.
