### ISSUE TITLE
Disable internal update check for distro packages

### ISSUE THREAD

**Issue by TheLastProject** [Pext/Pext#98]
Distro packages can update themselves. Pext shouldn't check for updates in them.

@vanyasem Any opinion on how to best make Pext know when it's running in a distro package?

**Comment by vanyasem** [comment]
In Arch we usually just apply a patch before building the package that disables updating *shrugs*

**Comment by TheLastProject** [comment]
I added 667567756545d502f563d46a9d1ac3bbe35289b6 to simplify such patching. Please set the constant USE_INTERNAL_UPDATER in pext/constants.py to False for the AUR packages.
